name: Run Tests

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Make script executable
        run: chmod +x test-script.sh

      - name: Run Test Script
        run: ./test-script.sh